spring:
  application:
    name: st-rest-server

  datasource:
    url: jdbc:mariadb://localhost:6033/encore?allowPublicKeyRetrieval=true&useSSL=false
    username: maria
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true